#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

# the base hostname & protocol for your site
url: "http://localhost:3000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Mathesi -  Protection of infrastructure system
# Website language
lang: en-US
# Header Title
header-title: Managing Risk
# Header Tagline
header-tagline: Mathesi

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Download Now
  url: https://themeforest.net/collections/6069390-sera

# Secondary Buttons
header-secondary-button:
  title: Discover More
  url: http://themeforest.net/user/gleesik

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: your_email@example.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://themeforest.net/collections/6069390-sera

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: John Doe
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Infersence Google Map
map-text-location: Athens, Greece
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
# about-title: Data Inference for decision support based on ML Sense.
about-title: About
#about-description: We deliver a range of direct consulting services and tailor made applications for customer-specific demands by bridging massive data assets with intuitive AI frameworks, forming decision support solutions. Capitalizing on solid experience in multi-disciplinary high-profile engineering research, Infersence aims to establish new boundaries in AI exploitation within higher order complexity processes of diverse domains. Stay ahead of your competition by introducing Infersence’s added value to your practices.
about-description: <p>Mathesi, derived from the Greek word "μάθηση" (pronounced "mathesi"), meaning "learning" or "knowledge," is a cutting-edge risk management and decision support enterprise specializing in the protection of infrastructure and short-term event predictions. Our mission is to improve safety and enhance the decision process in all environments.</p><p>We use state-of-the-art and proprietary data-driven and physical models to predict almost any risk-associated or beneficial parameter or event of interest, including e.g., meteorological conditions, hazardous conditions, system wear and fatigue, environmental quality, extreme events, or any other similar.</p><p>Furthermore, we implement AI algorithms to automate decision processes.</p>

#####################################
#############  Features  ############
#####################################
features-title: Features
features-description:

#
# Features
#
features:

# Feature
- title: Hyperlocal predictions
  description: Continuous forecasting of multiple parameters
  icon: pe-7s-vector

# Feature
- title: Risk & Gain Assessment
  description: Advanced evaluation of risk and gain of client-specified events/metrics
  icon: pe-7s-help2

# Feature
- title: Early Warning and AI
  description: Receive advanced warnings when fine-tuned thresholds and intervals are exceeded. Utilize AI for automated decisions
  icon: pe-7s-airplay

# Feature
# - title: Agile Software Development
  # description: Upgrading your everyday practises by adding pervasive AI-enhanced elements in critical components of your workflow.
  # icon: pe-7s-cloud child-center 



#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#
# Portfolio Grid
#
portfolio-categories: [Websites, Logo, Graphic Design, Development, Video, Photography]
portfolio:

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites, Graphic Design]
  image: img-01.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Graphic Design, Logo, Websites]
  image: img-02.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Graphic Design, Logo, Photography]
  image: img-03.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites, Video, Photography]
  image: img-04.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Development, Logo]
  image: img-05.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Development, Video]
  image: img-06.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites, Graphic Design]
  image: img-07.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites , Video]
  image: img-08.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Photography, Logo]
  image: img-09.jpg
  url: '#'


#####################################
##########  Optistructure  ##########
#####################################
optstructure-title: Optistructure
optstructure-description: <p>A <a href="http://www.optistructure.eu/" target="_blank">cloud-based</a> service designed by Infersence for incorporating sustainable design in the construction sector. OptiStructure service offers structural design optimization focusing on reducing embodied carbon in constructions via AI.</p>

#####################################
##########  Embryosense  ##########
#####################################
embryosense-title: Platform
embryosense-description: <p>The services of Mathesi are offered through a cloud application. The Mathesi App can be used directly through a complete, customizable and tailor-made browser-based UI.</p><p>The power of the platform can also be accessed using the Mathesi API, allowing for seamless integration with existing monitoring and warning systems.</p>

#####################################
##########  Research  ##########
#####################################
research-title: Research
research-description: <p>Develop a holistic machine learning aided optimum design and manufacturing process of civil structures through strong synergies among a multi-disciplinary team of academia and SMEs from Belgium, Cyprus, Germany, Greece, Italy, Jordan, Netherlands and Spain.<p>

#####################################
########### Testimonials ############
#####################################
testimonials-title: Meet Our Team
testimonials-description: The people behind Mathesi platform.

#
# Testimonials
#
testimonials:

# Client
- name: Christos T. Georgakis
  title: Managing Director, Board Member
  url: 'https://www.linkedin.com/in/chara-mitropoulou-a6a7093b/'
  url-text: LinkedIn
  avatar: georgakis.jpg
  cite: Is an active member of the computational earthquake engineering research community, focusing among others on performance-based earthquake engineering, structural design optimization of real-world structures and AI in structural engineering. Chara is the PI of IMSAFER.
  logo-img: themeforest.png

# Client
- name: Nikolaos Lagaros
  title: Board Member
  url: http://users.ntua.gr/nlagaros/
  url-text: Homepage
  avatar: lagaros.jpg
  cite: Nikos D. Lagaros, Dean of the School of Civil Engineering at the National Technical University of Athens, Director of the Personal Computers Laboratory, Professor of Structural Engineering. Nikos also served as Visiting Professor at MIT and McGill University. A focus of his consulting work is the assessment of buildings after earthquake events and the development of technical software for structural analysis and design optimization.
  logo-img: codecanyon.png

 # Client
- name: Cristoforo Demartino
  title: Board Member
  url: https://www.linkedin.com/in/nikos-kallioras-3695b27b/
  url-text: LinkedIn
  avatar: georgakis.jpg
  cite: ML/AI enthusiast, with experience on hands-on application of ML and optimization solutions, Co-founder of OptiStructure.
  logo-img: codecanyon.png 

# Client
- name: Panteleimon Tsakalis
  title: Software Developer (Machine Learning)
  url: https://www.linkedin.com/in/panteleimon-tsakalis-881ba413a/
  url-text: LinkedIn
  avatar: pantelis.jpg
  cite: Working on R&D in nanostructures and applied ML, programming geek, cloud-based databases developer.
  logo-img: videohive.png

# Client
- name: Ilias Chamatidis
  title: Machine Learning Engineer
  url: https://www.linkedin.com/in/ilias-chamatidis-840a011a4/
  url-text: LinkedIn
  avatar: chamatidis.jpg
  cite: Ilias Chamatidis is a researcher in the fields of topology optimization and artificial intelligence. He holds a Master's degree in Artificial Intelligence from Aristotle University of Thessaloniki and a Bachelor's degree in Computer Science. His interests are artificial intelligence, high performance computing, machine learning and algorithms.
  logo-img: videohive.png


#####################################
############# Our Blog ##############
#####################################
blog-title: Case Study
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.


#####################################
############### Team ################
#####################################
team-title: Meet Our Team
team-description: The people behind Mathesi platform.

#
# Team Members
#
team:

# Team Member
- name: Christos T. Georgakis
  tagline: Board <br> Member
  avatar: georgakis2.jpg
  email: georgakis@mathesi.com

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'
  linkedin : 'https://www.linkedin.com/in/christos-t-georgakis-55b062a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app'

# Team Member
- name: Nikolaos Lagaros
  tagline: Board <br> Member
  avatar: lagaros2.png
  email: lagaros@mathesi.com

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'
  linkedin: https://gr.linkedin.com/in/nikos-lagaros-086323?original_referer=

# Team Member
- name: Cristoforo Demartino
  tagline: Board <br> Member
  avatar: demartino2.jpg
  email: demartino@mathesi.com

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'
  linkedin: https://cn.linkedin.com/in/cristoforo-demartino-00257231

# Team Member
- name: Panteleimon Tsakalis
  tagline: Software Developer (Machine Learning)
  avatar: pantelis2.png
  email: tsakalis@mathesi.com

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'
  linkedin: 'https://www.linkedin.com/in/panteleimon-tsakalis-881ba413a/'

# Team Member
- name: Ilias Chamatidis
  tagline: Machine Learning <br> Engineer
  avatar: chamatidis2.png
  email: chamatidis@mathesi.com

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'
  linkedin: 'https://www.linkedin.com/in/ilias-chamatidis-840a011a4/'


#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Pricing Tables
pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Plan Personal
#
plan-personal-price: $99
plan-personal-offer-1-title: 01 PSD Pack
plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: '#'

#
# Plan Business
#
plan-business-price: $499
plan-business-offer-1-title: 05 PSD Pack
plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: '#'

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: '#'


#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: Mathesi <br> Ullerødvej 9 2980 Kokkedal <br> support@mathesi.com



#####################################
#############   Footer   ############
#####################################
footer-description: Mathesi - Protection of infrastructure system
footer-copyright-text: Mathesi&trade;
footer-copyright-url: http://www.mathesi.com/
footer-copyright-year: 2023
